/* Generated by itemis CREATE code generator. */


#include "../src/sc_types.h"

#include "Statechart.h"
#include "Statechart_required.h"

/*! \file
Implementation of the state machine 'Statechart'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */
static void enact_main_region_SampleRequestedADC(Statechart* handle);
static void enact_main_region_SampleReadingADC(Statechart* handle);
static void enact_main_region_DisplayData(Statechart* handle);
static void enact_main_region_UARTtransmit(Statechart* handle);
static void exact_main_region_SampleReadingADC(Statechart* handle);
static void exact_main_region_DisplayData(Statechart* handle);
static void enseq_main_region_WaitSamplePeriod_default(Statechart* handle);
static void enseq_main_region_SampleRequestedADC_default(Statechart* handle);
static void enseq_main_region_SampleReadingADC_default(Statechart* handle);
static void enseq_main_region_DisplayData_default(Statechart* handle);
static void enseq_main_region_UARTtransmit_default(Statechart* handle);
static void enseq_main_region_default(Statechart* handle);
static void exseq_main_region_WaitSamplePeriod(Statechart* handle);
static void exseq_main_region_SampleRequestedADC(Statechart* handle);
static void exseq_main_region_SampleReadingADC(Statechart* handle);
static void exseq_main_region_DisplayData(Statechart* handle);
static void exseq_main_region_UARTtransmit(Statechart* handle);
static void exseq_main_region(Statechart* handle);
static void react_main_region__entry_Default(Statechart* handle);

/*! The reactions of state WaitSamplePeriod. */
static sc_integer main_region_WaitSamplePeriod_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state SampleRequestedADC. */
static sc_integer main_region_SampleRequestedADC_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state SampleReadingADC. */
static sc_integer main_region_SampleReadingADC_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state DisplayData. */
static sc_integer main_region_DisplayData_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state UARTtransmit. */
static sc_integer main_region_UARTtransmit_react(Statechart* handle, const sc_integer transitioned_before);


static void clear_in_events(Statechart* handle);

static void micro_step(Statechart* handle);

/*! Performs a 'run to completion' step. */
static void run_cycle(Statechart* handle);




static void statechart_internal_set_channel_no(Statechart* handle, sc_integer value)
;
static void statechart_internal_set_sample_no(Statechart* handle, sc_integer value)
;


static void statechart_eventqueue_init(statechart_eventqueue * eq, statechart_event *buffer, sc_integer capacity);
static sc_integer statechart_eventqueue_size(statechart_eventqueue * eq);
static void statechart_event_init(statechart_event * ev, StatechartEventID name);
static statechart_event statechart_eventqueue_pop(statechart_eventqueue * eq);
static sc_boolean statechart_eventqueue_push(statechart_eventqueue * eq, statechart_event ev);
static void statechart_add_event_to_queue(statechart_eventqueue * eq, StatechartEventID name);
static sc_boolean statechart_dispatch_event(Statechart* handle, const statechart_event * event);
static statechart_event statechart_get_next_event(Statechart* handle);
static sc_boolean statechart_dispatch_next_event(Statechart* handle);


void statechart_init(Statechart* handle)
{
	sc_integer i;
	
	for (i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Statechart_last_state;
	}
	
				
	clear_in_events(handle);
	
	
	/* Default init sequence for statechart Statechart */
	statechart_internal_set_channel_no(handle, 0);
	statechart_internal_set_sample_no(handle, 0);
	
	handle->isExecuting = bool_false;
	statechart_eventqueue_init(&handle->in_event_queue, handle->in_buffer, STATECHART_IN_EVENTQUEUE_BUFFERSIZE);
}

void statechart_enter(Statechart* handle)
{
	/* Activates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart Statechart */
	enseq_main_region_default(handle);
	handle->doCompletion = bool_false;
	do
	{ 
		if (handle->completed == bool_true)
		{ 
			handle->doCompletion = bool_true;
		} 
		handle->completed = bool_false;
		micro_step(handle);
		clear_in_events(handle);
		handle->doCompletion = bool_false;
	} while (handle->completed == bool_true);
	handle->isExecuting = bool_false;
}

void statechart_exit(Statechart* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart Statechart */
	exseq_main_region(handle);
	handle->stateConfVector[0] = Statechart_last_state;
	handle->isExecuting = bool_false;
}

/*!
Can be used by the client code to trigger a run to completion step without raising an event.
*/
void statechart_trigger_without_event(Statechart* handle) {
	run_cycle(handle);
}


sc_boolean statechart_is_active(const Statechart* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Statechart_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean statechart_is_final(const Statechart* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

sc_boolean statechart_is_state_active(const Statechart* handle, StatechartStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Statechart_main_region_WaitSamplePeriod :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_WAITSAMPLEPERIOD] == Statechart_main_region_WaitSamplePeriod
			);
				break;
		case Statechart_main_region_SampleRequestedADC :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_SAMPLEREQUESTEDADC] == Statechart_main_region_SampleRequestedADC
			);
				break;
		case Statechart_main_region_SampleReadingADC :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_SAMPLEREADINGADC] == Statechart_main_region_SampleReadingADC
			);
				break;
		case Statechart_main_region_DisplayData :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_DISPLAYDATA] == Statechart_main_region_DisplayData
			);
				break;
		case Statechart_main_region_UARTtransmit :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_UARTTRANSMIT] == Statechart_main_region_UARTtransmit
			);
				break;
			default:
				result = bool_false;
				break;
		}
		return result;
	}

static void clear_in_events(Statechart* handle)
{
	handle->iface.Ev_GetSample_raised = bool_false;
	handle->iface.Ev_ADCSampleReady_raised = bool_false;
}

static void micro_step(Statechart* handle)
{
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region_WaitSamplePeriod :
		{
			main_region_WaitSamplePeriod_react(handle,-1);
			break;
		}
		case Statechart_main_region_SampleRequestedADC :
		{
			main_region_SampleRequestedADC_react(handle,-1);
			break;
		}
		case Statechart_main_region_SampleReadingADC :
		{
			main_region_SampleReadingADC_react(handle,-1);
			break;
		}
		case Statechart_main_region_DisplayData :
		{
			main_region_DisplayData_react(handle,-1);
			break;
		}
		case Statechart_main_region_UARTtransmit :
		{
			main_region_UARTtransmit_react(handle,-1);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

static void run_cycle(Statechart* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	statechart_dispatch_next_event(handle);
	do
	{ 
		handle->doCompletion = bool_false;
		do
		{ 
			if (handle->completed == bool_true)
			{ 
				handle->doCompletion = bool_true;
			} 
			handle->completed = bool_false;
			micro_step(handle);
			clear_in_events(handle);
			handle->doCompletion = bool_false;
		} while (handle->completed == bool_true);
	} while (statechart_dispatch_next_event(handle) == bool_true);
	handle->isExecuting = bool_false;
}


void statechart_raise_ev_GetSample(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_Ev_GetSample);
	run_cycle(handle);
}

void statechart_raise_ev_ADCSampleReady(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_Ev_ADCSampleReady);
	run_cycle(handle);
}




static void statechart_internal_set_channel_no(Statechart* handle, sc_integer value)
{
	handle->internal.channel_no = value;
}
static void statechart_internal_set_sample_no(Statechart* handle, sc_integer value)
{
	handle->internal.sample_no = value;
}


/* implementations of all internal functions */

/* Entry action for state 'SampleRequestedADC'. */
static void enact_main_region_SampleRequestedADC(Statechart* handle)
{
	/* Entry action for state 'SampleRequestedADC'. */
	statechart_startConvADC(handle,handle->internal.channel_no);
}

static void enact_main_region_SampleReadingADC(Statechart* handle)
{
	/* Entry action for state 'SampleReadingADC'. */
	statechart_readADCSample(handle,handle->internal.channel_no);
	handle->completed = bool_true;
}

static void enact_main_region_DisplayData(Statechart* handle)
{
	/* Entry action for state 'DisplayData'. */
	statechart_processData(handle);
	statechart_displayInfo(handle);
	handle->completed = bool_true;
}

static void enact_main_region_UARTtransmit(Statechart* handle)
{
	/* Entry action for state 'UARTtransmit'. */
	statechart_transmitReadings(handle);
	handle->completed = bool_true;
}

/* Exit action for state 'SampleReadingADC'. */
static void exact_main_region_SampleReadingADC(Statechart* handle)
{
	/* Exit action for state 'SampleReadingADC'. */
	statechart_saveADCSample(handle,handle->internal.channel_no, handle->internal.sample_no);
	statechart_internal_set_channel_no(handle, (handle->internal.channel_no + 1));
}

/* Exit action for state 'DisplayData'. */
static void exact_main_region_DisplayData(Statechart* handle)
{
	/* Exit action for state 'DisplayData'. */
	statechart_internal_set_sample_no(handle, 0);
}

/* 'default' enter sequence for state WaitSamplePeriod */
static void enseq_main_region_WaitSamplePeriod_default(Statechart* handle)
{
	/* 'default' enter sequence for state WaitSamplePeriod */
	handle->stateConfVector[0] = Statechart_main_region_WaitSamplePeriod;
}

/* 'default' enter sequence for state SampleRequestedADC */
static void enseq_main_region_SampleRequestedADC_default(Statechart* handle)
{
	/* 'default' enter sequence for state SampleRequestedADC */
	enact_main_region_SampleRequestedADC(handle);
	handle->stateConfVector[0] = Statechart_main_region_SampleRequestedADC;
}

/* 'default' enter sequence for state SampleReadingADC */
static void enseq_main_region_SampleReadingADC_default(Statechart* handle)
{
	/* 'default' enter sequence for state SampleReadingADC */
	enact_main_region_SampleReadingADC(handle);
	handle->stateConfVector[0] = Statechart_main_region_SampleReadingADC;
}

/* 'default' enter sequence for state DisplayData */
static void enseq_main_region_DisplayData_default(Statechart* handle)
{
	/* 'default' enter sequence for state DisplayData */
	enact_main_region_DisplayData(handle);
	handle->stateConfVector[0] = Statechart_main_region_DisplayData;
}

/* 'default' enter sequence for state UARTtransmit */
static void enseq_main_region_UARTtransmit_default(Statechart* handle)
{
	/* 'default' enter sequence for state UARTtransmit */
	enact_main_region_UARTtransmit(handle);
	handle->stateConfVector[0] = Statechart_main_region_UARTtransmit;
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(Statechart* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* Default exit sequence for state WaitSamplePeriod */
static void exseq_main_region_WaitSamplePeriod(Statechart* handle)
{
	/* Default exit sequence for state WaitSamplePeriod */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state SampleRequestedADC */
static void exseq_main_region_SampleRequestedADC(Statechart* handle)
{
	/* Default exit sequence for state SampleRequestedADC */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state SampleReadingADC */
static void exseq_main_region_SampleReadingADC(Statechart* handle)
{
	/* Default exit sequence for state SampleReadingADC */
	handle->stateConfVector[0] = Statechart_last_state;
	exact_main_region_SampleReadingADC(handle);
}

/* Default exit sequence for state DisplayData */
static void exseq_main_region_DisplayData(Statechart* handle)
{
	/* Default exit sequence for state DisplayData */
	handle->stateConfVector[0] = Statechart_last_state;
	exact_main_region_DisplayData(handle);
}

/* Default exit sequence for state UARTtransmit */
static void exseq_main_region_UARTtransmit(Statechart* handle)
{
	/* Default exit sequence for state UARTtransmit */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for region main region */
static void exseq_main_region(Statechart* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of Statechart.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region_WaitSamplePeriod :
		{
			exseq_main_region_WaitSamplePeriod(handle);
			break;
		}
		case Statechart_main_region_SampleRequestedADC :
		{
			exseq_main_region_SampleRequestedADC(handle);
			break;
		}
		case Statechart_main_region_SampleReadingADC :
		{
			exseq_main_region_SampleReadingADC(handle);
			break;
		}
		case Statechart_main_region_DisplayData :
		{
			exseq_main_region_DisplayData(handle);
			break;
		}
		case Statechart_main_region_UARTtransmit :
		{
			exseq_main_region_UARTtransmit(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(Statechart* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_WaitSamplePeriod_default(handle);
}


static sc_integer main_region_WaitSamplePeriod_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state WaitSamplePeriod. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (0))
		{ 
			if (handle->iface.Ev_GetSample_raised == bool_true)
			{ 
				exseq_main_region_WaitSamplePeriod(handle);
				enseq_main_region_SampleRequestedADC_default(handle);
				transitioned_after = 0;
			} 
		} 
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = transitioned_before;
		} 
	} return transitioned_after;
}

static sc_integer main_region_SampleRequestedADC_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state SampleRequestedADC. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (0))
		{ 
			if (handle->iface.Ev_ADCSampleReady_raised == bool_true)
			{ 
				exseq_main_region_SampleRequestedADC(handle);
				enseq_main_region_SampleReadingADC_default(handle);
				transitioned_after = 0;
			} 
		} 
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = transitioned_before;
		} 
	} return transitioned_after;
}

static sc_integer main_region_SampleReadingADC_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state SampleReadingADC. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state SampleReadingADC */
		handle->stateConfVector[0] = Statechart_last_state;
		exact_main_region_SampleReadingADC(handle);
		/* The reactions of state null. */
		if ((handle->internal.channel_no) == (2))
		{ 
			statechart_internal_set_channel_no(handle, 0);
			statechart_internal_set_sample_no(handle, (handle->internal.sample_no + 1));
			enseq_main_region_UARTtransmit_default(handle);
		}  else
		{
			enseq_main_region_SampleRequestedADC_default(handle);
		}
	}  else
	{
		/* Always execute local reactions. */
		transitioned_after = transitioned_before;
	}
	return transitioned_after;
}

static sc_integer main_region_DisplayData_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state DisplayData. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state DisplayData */
		handle->stateConfVector[0] = Statechart_last_state;
		exact_main_region_DisplayData(handle);
		/* 'default' enter sequence for state WaitSamplePeriod */
		handle->stateConfVector[0] = Statechart_main_region_WaitSamplePeriod;
	}  else
	{
		/* Always execute local reactions. */
		transitioned_after = transitioned_before;
	}
	return transitioned_after;
}

static sc_integer main_region_UARTtransmit_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state UARTtransmit. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state UARTtransmit */
		handle->stateConfVector[0] = Statechart_last_state;
		/* The reactions of state null. */
		if ((handle->internal.sample_no) == (10))
		{ 
			enseq_main_region_DisplayData_default(handle);
		}  else
		{
			enseq_main_region_WaitSamplePeriod_default(handle);
		}
	}  else
	{
		/* Always execute local reactions. */
		transitioned_after = transitioned_before;
	}
	return transitioned_after;
}




static void statechart_eventqueue_init(statechart_eventqueue * eq, statechart_event *buffer, sc_integer capacity)
{
	eq->events = buffer;
	eq->capacity = capacity;
	eq->push_index = 0;
	eq->pop_index = 0;
	eq->size = 0;
}

static sc_integer statechart_eventqueue_size(statechart_eventqueue * eq)
{
	return eq->size;
}

static statechart_event statechart_eventqueue_pop(statechart_eventqueue * eq)
{
	statechart_event event;
	if(statechart_eventqueue_size(eq) <= 0) {
		statechart_event_init(&event, Statechart_invalid_event);
	}
	else {
		event = eq->events[eq->pop_index];
		
		if(eq->pop_index < eq->capacity - 1) {
			eq->pop_index++;
		} 
		else {
			eq->pop_index = 0;
		}
		eq->size--;
	}
	return event;
}
static sc_boolean statechart_eventqueue_push(statechart_eventqueue * eq, statechart_event ev)
{
	if(statechart_eventqueue_size(eq) == eq->capacity) {
		return bool_false;
	}
	else {
		eq->events[eq->push_index] = ev;
		
		if(eq->push_index < eq->capacity - 1) {
			eq->push_index++;
		}
		else {
			eq->push_index = 0;
		}
		eq->size++;
		
		return bool_true;
	}
}
static void statechart_event_init(statechart_event * ev, StatechartEventID name)
{
	ev->name = name;
}

static void statechart_add_event_to_queue(statechart_eventqueue * eq, StatechartEventID name)
{
	statechart_event event;
	statechart_event_init(&event, name);
	statechart_eventqueue_push(eq, event);
}

static sc_boolean statechart_dispatch_event(Statechart* handle, const statechart_event * event) {
	switch(event->name) {
		case Statechart_Ev_GetSample:
		{
			handle->iface.Ev_GetSample_raised = bool_true;
			return bool_true;
		}
		case Statechart_Ev_ADCSampleReady:
		{
			handle->iface.Ev_ADCSampleReady_raised = bool_true;
			return bool_true;
		}
		default:
			return bool_false;
	}
}

static statechart_event statechart_get_next_event(Statechart* handle)
{
	statechart_event next_event;
	statechart_event_init(&next_event, Statechart_invalid_event);
	if(statechart_eventqueue_size(&(handle->in_event_queue)) > 0) {
		next_event = statechart_eventqueue_pop(&(handle->in_event_queue));
	}
	return next_event;
}

static sc_boolean statechart_dispatch_next_event(Statechart* handle)
{
	statechart_event nextEvent;
	nextEvent = statechart_get_next_event(handle);
	return statechart_dispatch_event(handle, &nextEvent);
}
